# Eureka Server ?? ????? ???? port
server:
  port: 8761

eureka:
  client:
    # Eureka Server? ??? ???? ??? ?? (?? ??? Server?? ??)
    register-with-eureka: false
    # Eureka Server?? Service Registry? ???? ??? ?? (?? Service? ????? ???? ??? ??? ??)
    fetch-registry: false

    service-url:
      defaultZone: http://localhost:8761/eureka