# client? ????? gateway? port? ???? ????.
server:
  port: 8000

spring:
  application:
    # application ?? ??
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: team
          uri: lb://team
          predicates:
            - Path=/team/**
          filters:
            - RewritePath=/team/(?<segment>.*), /$\{segment}

        - id: project
          uri: lb://project
          predicates:
            - Path=/project/**
          filters:
            - RewritePath=/project/(?<segment>.*), /$\{segment}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka